version: "3"
services:
 frontend:
    image: 00bdc164bd72
    ports:
      - "5501:80"
    networks:
    - connect
    depends_on:
      - backend

 backend:
   image: 78b9511bcc23
   ports:
      - "8000:8000"
   networks:
      - connect
   
 server:
    image: 79a1efef400b
    ports:
      - 12345:12345

 zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

 kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    depends_on:
      - zookeeper

 producer:
    image: c41cf0b0dcc3
    depends_on:
      kafka:
        condition: service_healthy


 consumer:
    image: e89341b65053
    depends_on:
      kafka:
        condition: service_healthy

networks:
  connect:
    driver: bridge    